version: '3.1'
services:

  db:
    image: postgres:14
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - /home/erickluz/dev/projects/workspaces/systrip-spring/source/driver/deploy/script/driver.sql:/docker-entrypoint-initdb.d/driver.sql
      - /home/erickluz/dev/projects/workspaces/systrip-spring/source/trip/deploy/script/trip.sql:/docker-entrypoint-initdb.d/trip.sql
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    container_name: rabbitmq
    ports: 
      - "8080:8080"
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: adm
      RABBITMQ_DEFAULT_PASS: adm
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
