version: '3.1'
services:

  db:
    image: postgres:14
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - type: bind
        source: ./driver/deploy/script/driver.sql
        target: /docker-entrypoint-initdb.d/driver.sql
        volume:
          nocopy: true  # flag to disable copying of data from a container when a volume is created
      - type: bind
        source: ./passenger/deploy/script/passenger.sql
        target: /docker-entrypoint-initdb.d/passenger.sql
        volume:
          nocopy: true  # flag to disable copying of data from a container when a volume is created
      - type: bind
        source: ./trip/deploy/script/trip.sql
        target: /docker-entrypoint-initdb.d/trip.sql
        volume:
          nocopy: true  # flag to disable copying of data from a container when a volume is created
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    container_name: rabbitmq
    ports: 
      - "8080:8080"
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: adm
      RABBITMQ_DEFAULT_PASS: adm
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  reddis:
    image: redis:7.0.5
    restart: always
    ports:
        - "6379:6379"
