apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-systrip
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-systrip
  template:
    metadata:
      labels:
        app: driver-systrip
    spec:
      containers:
      - env:
        - name: POSTGRES_DRIVER_DB_URL
          value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/driver"
        - name: USER_BD
          value: "postgres"
        - name: PASSWORD_BD
          value: "root"
        - name: RABBIT_ADDRESS
          value: "hello-world"
        - name: RABIT_USER
          value: "adm"
        - name: RABIT_PASSWORD
          value: "adm"
        - name: DRIVER_PORT
          value: "8082"
        image: erickluz360/driver
        imagePullPolicy: "Always"
        name: driver-systrip
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: driver-systrip
  name: driver-systrip
  namespace: default
spec:
  ports:
  - name: driver-port
    nodePort: 30180
    port: 8082
    targetPort: 8082
  selector:
    app: driver-systrip
  type: NodePort
