apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger-systrip
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passenger-systrip
  template:
    metadata:
      labels:
        app: passenger-systrip
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: POSTGRES_PASSENGER_DB_URL
          value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/passenger"
        - name: USER_BD
          value: "postgres"
        - name: PASSWORD_BD
          value: "root"
        - name: RABBIT_ADDRESS
          value: "hello-world"
        - name: RABIT_USER
          value: "adm"
        - name: RABIT_PASSWORD
          value: "adm"
        - name: PASSENGER_PORT
          value: "8084"
        image: erickluz360/passenger
        imagePullPolicy: "Always"
        name: passenger-systrip
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: passenger-systrip
  name: passenger-systrip
  namespace: default
spec:
  ports:
  - name: passenger-port
    nodePort: 30181
    port: 8084
    targetPort: 8084
  selector:
    app: passenger-systrip
  type: NodePort
